config/routes.rb
Rails.application.routes.draw do
  

  get "programming" => "posts#programming"
  get "health_and_beauty" => "posts#health_and_beauty"
  get "eat_and_drink" => "posts#eat_and_drink"
  get "book" => "posts#book"
  get "other" => "posts#other"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :posts
  root "home#index"
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  SECTIONS = ["Health and Beauty", "Programming", "Book", "Eat and Drink", "Other"]
  enum section: SECTIONS
  validates :title, :content, :section, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def new
  end

  def create 
    @post = Post.new(post_params)
    if @post.save 
      redirect_to root_path
    else 
      render "new"
    end 
  end 

  def post_params
    params.require(:post).permit(:title, :section, :content)
  end 

  def health_and_beauty
    @posts = Post.where(section: "Health and Beauty")
  end 

  def programming
    @posts = Post.where(section: "Programming") 
  end 

  def book 
    @posts = Post.where(section: "Book")
  end 

  def eat_and_drink
    @posts = Post.where(section: "Eat and Drink")
  end 

  def other 
    @posts = Post.where(section: "Other")
  end 


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/home/index.html.erb
<div class="columns welcome-wall">
  <div class="column left-wall">
    <p>Test 1</p>
  </div>
  <div class="column right-wall">
    <p>Test 2</p>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ChuyencuaQuy</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
  </head>

  <body>
    <div class="container">
      <div class="navbar">
        <div class="navbar-brand">
          <div class="navbar-item">
            <%= link_to "Home", root_path %>
          </div>
          <div class="navbar-item">
            <%= link_to "Create Post", new_post_path %>
          </div>
          <div class="navbar-item">
            <%= link_to "Programming", programming_path %>
          </div>
          <div class="navbar-item">
            <%= link_to "Health&Beauty", health_and_beauty_path %>
          </div>
          <div class="navbar-item">
            <%= link_to "Eat&Drink", eat_and_drink_path %>
          </div>
          <div class="navbar-item">
            <%= link_to "Book", book_path %>
          </div>
          <div class="navbar-item">
            <%= link_to "Other", other_path %>
          </div>
        </div>
        <div class="navbar-menu">
          <div class="navbar-start">
          </div>
        </div>
      </div>
      <%= yield %>
    </div>
  </body>
</html>

app/views/posts/new.html.erb
<div class="columns is-centered">
  <div class="column is-6 ">
    <div class="card">
    <div class="card-header">
      <div class="card-header-title">
      LOVE
      </div>
    </div>
      <%= form_for Post.new do |f| %>
        <div class="field">
          <div class="control">
            <%= f.text_field :title, placeholder: "Title" %>
          </div>
        </div>
        <div class="field">
          <%= f.text_area :content, placeholder: "Content" %>
        </div>
        <div class="field">
          <div class="control">
            <span class="select">
              <%= f.select(:section, Post::SECTIONS.map {|section| section })%>
            </span>
          </div>
        </div>
        <%= f.submit "Submit", class: "button is-primary" %>
      <% end %>
    </div>
  </div>
</div>